name: Duels
main: me.realized.duels.Core
version: 2.2.2

author: Realized
website: https://www.spigotmc.org/resources/duels.20171/
description: An ultimate solution to server owners wanting to create a duel system.

softdepend: [WorldGuard, Multiverse-Core, Essentials, Factions, mcMMO, MVdWPlaceholderAPI]

# Multiverse-Core added as soft-depend due to locations being null when Duels is loaded first.
# Add any world management plugins to softdepend list if arena doesn't load properly in the generated world.

commands:
   duel:
     description: Send, accept, or deny a duel request.
     aliases: [1v1]
   stats:
     description: Display stats of yours or others.
     aliases: [statistics, info, duelstats, dstats]
   spectate:
     description: Spectate a player in duel.
     aliases: [spec]
   queue:
     description: Join the duels queue.
     aliases: [joinqueue, duelsqueue, duelqueue, fastduel]
   toggle:
     description: Enable or disable receiving duel requests.
     aliases: [tg]
   duels:
     description: Administrative commands of Duels.
     aliases: [ds]

permissions:
  duels.*:
    children:
      duels.admin: true

  duels.default:
    children:
      duels.queue: true
      duels.duel: true
      duels.stats: true
      duels.toggle: true

  duels.admin:
    children:
      duels.default: true
      duels.spectate: true
      duels.spectate.anonymously: true